# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ab818f3823c4c0764c84eb1e6eb1a2da"
name = "csv-cart-builder"
handle = "csv-cart-builder"
application_url = "https://louisville-massage-best-thinkpad.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://louisville-massage-best-thinkpad.trycloudflare.com/auth/callback", "https://louisville-massage-best-thinkpad.trycloudflare.com/auth/shopify/callback", "https://louisville-massage-best-thinkpad.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
